# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/untitled_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 90, 781, 321))
        self.tableView.setStyleSheet("QTableView{\n"
"    background-color:     #FFFFFF;\n"
"    border: 2px outset     #23272A;\n"
"    border-radius: 5px;\n"
"    color: rgb(0, 0, 0);\n"
"    selection-background-color: rgb(114, 137, 218);\n"
"}\n"
"")
        self.tableView.setObjectName("tableView")
        self.start_date = QtWidgets.QComboBox(self.centralwidget)
        self.start_date.setGeometry(QtCore.QRect(8, 450, 131, 26))
        self.start_date.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_date.setStyleSheet("QComboBox{\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"}\n"
"QComboBox::off{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(114, 137, 218);\n"
"}\n"
"QComboBox::on{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(114, 137, 218);\n"
"}\n"
"QComboBox QListView{\n"
"    \n"
"    background-color: rgb(68, 68, 68);\n"
"}")
        self.start_date.setObjectName("start_date")
        self.end_date = QtWidgets.QComboBox(self.centralwidget)
        self.end_date.setGeometry(QtCore.QRect(160, 450, 131, 26))
        self.end_date.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.end_date.setStyleSheet("QComboBox{\n"
"    border-radius: 5px;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 68, 68);\n"
"}\n"
"QComboBox::off{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(114, 137, 218);\n"
"}\n"
"QComboBox::on{\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-color: rgb(114, 137, 218);\n"
"}\n"
"QComboBox QListView{\n"
"    \n"
"    background-color: rgb(68, 68, 68);\n"
"}")
        self.end_date.setObjectName("end_date")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 454, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 430, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 430, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.view_table = QtWidgets.QPushButton(self.centralwidget)
        self.view_table.setGeometry(QtCore.QRect(10, 490, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.view_table.setFont(font)
        self.view_table.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_table.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #7289DA;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(151, 168, 226);\n"
"}")
        self.view_table.setObjectName("view_table")
        self.start_printer = QtWidgets.QPushButton(self.centralwidget)
        self.start_printer.setGeometry(QtCore.QRect(10, 540, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start_printer.setFont(font)
        self.start_printer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_printer.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #7289DA;\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"QPushButton::hover{\n"
"\n"
"    background-color: rgb(151, 168, 226);\n"
"}")
        self.start_printer.setObjectName("start_printer")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(300, 410, 481, 181))
        self.label_5.setStyleSheet("image: url(images/sleep);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(770, 0, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("QPushButton{\n"
"    background-color: rgba(191, 64, 64, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"}")
        self.exit.setObjectName("exit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:     #323339;\n"
"border-radius: 10px;")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_6.raise_()
        self.label.raise_()
        self.tableView.raise_()
        self.start_date.raise_()
        self.end_date.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.view_table.raise_()
        self.start_printer.raise_()
        self.label_5.raise_()
        self.exit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Отчёт"))
        self.label_2.setText(_translate("MainWindow", ">"))
        self.label_3.setText(_translate("MainWindow", "Начальная дата"))
        self.label_4.setText(_translate("MainWindow", "Конечная дата"))
        self.view_table.setText(_translate("MainWindow", "Вывести"))
        self.start_printer.setText(_translate("MainWindow", "Печать"))
        self.exit.setText(_translate("MainWindow", "×"))
